import Head from 'next/head';
import Link from 'next/link';
import axios from 'axios';

export default function About(props) {
    return (
        <>
            <Head>
                <title>About - Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>About page</h1>
            <div>{JSON.stringify(props.data, null, 2)}</div>
            <Link href="/">
                <a>Home page</a>
            </Link>
        </>
    );
}

export async function getServerSideProps() {
    const { data } = await axios.get(`http://backend/api`);

    // Pass data to the page via props
    return { props: { data } };
}
