import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layouts/default';

export default function IndexPage() {
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <h1>Home page</h1>
            <Link href="/about">
                <a>About page</a>
            </Link>
        </Layout>
    );
}
