import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';
import Layout from '../components/layouts/default';

export default function IndexPage() {
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <h1>Home page</h1>
            <Link href="/about">
                <a>About page</a>
            </Link>
            <div style={{ maxWidth: 1000 }}>
                <Image
                    src="/complex.png"
                    priority={true}
                    width={1478}
                    height={687}
                    layout="responsive"
                    quality={80}
                    alt=""
                />
            </div>
        </Layout>
    );
}
